name: ci

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install
      - run: yarn dev:prepare
      - run: yarn lint
      - run: yarn build

      - name: Publish
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '[skip-release]')
        run:
          yarn dlx -p semantic-release -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/changelog -p @semantic-release/npm -p @semantic-release/git -p @semantic-release/github semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
